# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = shulkersinbundles
mod_name = ShulkersInBundles
mod_version = 1.2.2
mod_description = Making bundles a little bit more convenient and useful by allowing to put shulkers in them
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.shulkersinbundles
archives_base_name = ShulkersInBundles

minecraft_version_constraint_forge = [26.1,)
minecraft_version_constraint_fabric = >=26.1-alpha.3
supported_versions = *

# Publishing
publish.modrinth = [MODRINTH_MOD_ID]
publish.curseforge = [CURSEFORGE_MOD_ID]
