# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version=1.2.2
maven_group=net.justmili
archives_name=shulkersinbundles
display_name = ShulkersInBundles
enabled_platforms=fabric,forge,neoforge

# Minecraft properties
minecraft_version = 1.21.11
min_minecraft_version = 1.21.2

# Dependencies
fabric_loader_version = 0.17.0
forge_version = 1.21.11-61.0.3
forge_version_range = 52
neoforge_version = 21.11.6-beta
neo_version_range = 21.2