[versions]
minecraft = "26.3"

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge = "66.0.3"
# https://projects.neoforged.net/neoforged/neoforge
neoforge = "26.3.0.16-beta"

# https://fabricmc.net/develop
fabric_loader = "0.19.3"
fabric_loom = "1.17-SNAPSHOT"

# https://projects.neoforged.net/neoforged/moddevgradle
moddevgradle = "2.0.147"

# https://files.minecraftforge.net/net/minecraftforge/forgegradle/index.html
forge_gradle = "7.0.40"
# https://files.minecraftforge.net/net/minecraftforge/jarjar-gradle/index.html
forge_jarjar = "0.2.3"

# https://github.com/GradleUp/shadow/releases
shadow = "9.4.1"
# https://modmuss50.github.io/mod-publish-plugin/
mod_publish = "2.2.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
forge_gradle = { id = "net.minecraftforge.gradle", version.ref = "forge_gradle" }
forge_jarjar = { id = "net.minecraftforge.jarjar", version.ref = "forge_jarjar" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
mod_publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod_publish" }