modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/Lumynity-Studios/ShulkersInBundles/issues"
license = "MIT"

[[mods]]
modId = "shulkersinbundles"
version = "${mod_version}"
displayName = "Shulkers In Bundles"
authors = "JustMili"
description = '''
Making bundles a little bit more convenient and useful by allowing to put shulkers in them
'''
logoFile = "icon.png"

[[dependencies.shulkersinbundles]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,1.21.11]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "shulkersinbundles.mixins.json"
